DEBUG - 2025-05-08 11:03:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 11:03:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 11:03:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 11:03:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 11:09:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-05-08 12:32:19 --> CodeIgniter\Filters\Exceptions\FilterException: "auth" filter must have a matching alias defined.
[Method: GET, Route: tareas]
in SYSTEMPATH\Filters\Filters.php on line 590.
 1 SYSTEMPATH\Filters\Filters.php(590): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
 2 SYSTEMPATH\Filters\Filters.php(641): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
 3 SYSTEMPATH\CodeIgniter.php(467): CodeIgniter\Filters\Filters->enableFilters([...], 'before')
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-08 14:01:02 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#9 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#6 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-05-08 14:01:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: tareas]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Tareas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TareaController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-08 14:04:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'SistemaGestionT...', 3306, '', 0)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#9 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#6 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-05-08 14:04:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: tareas]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Tareas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TareaController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-08 14:04:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'SistemaGestionT...', 3306, '', 0)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#9 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#6 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-05-08 14:04:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: tareas]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Tareas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TareaController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-08 14:04:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'SistemaGestionT...', 3306, '', 0)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#9 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#6 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-05-08 14:04:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: tareas]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Tareas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TareaController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-08 17:11:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'SistemaGestionT...', 3306, '', 0)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#9 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#6 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-05-08 17:11:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: tareas]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Tareas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TareaController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-08 17:18:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'SistemaGestionT...', 3306, '', 0)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#9 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#6 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-05-08 17:18:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: tareas]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Tareas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TareaController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-08 17:23:20 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'SistemaGestionT...', 3306, '', 0)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#9 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 G:\xampp\htdocs\framework-ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
#6 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->index()
#7 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#8 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-05-08 17:23:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: tareas]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Tareas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TareaController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TareaController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-08 19:03:08 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`sistemagestiontareas`.`tareas`, CONSTRAINT `tareas_ibfk_4` FOREIGN KEY (`id_propietario`) REFERENCES `usuarios` (`id_usuario`)) in G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 G:\xampp\htdocs\framework-ci4\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `Ta...', 0)
#1 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Ta...')
#2 G:\xampp\htdocs\framework-ci4\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Ta...')
#3 G:\xampp\htdocs\framework-ci4\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Ta...', Array, false)
#4 G:\xampp\htdocs\framework-ci4\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp\htdocs\framework-ci4\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 G:\xampp\htdocs\framework-ci4\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 G:\xampp\htdocs\framework-ci4\app\Controllers\TareaController.php(23): CodeIgniter\BaseModel->save(Array)
#9 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(933): App\Controllers\TareaController->guardar()
#10 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
#11 G:\xampp\htdocs\framework-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 G:\xampp\htdocs\framework-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 G:\xampp\htdocs\framework-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 G:\xampp\htdocs\framework-ci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-08 19:03:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`sistemagestiontareas`.`tareas`, CONSTRAINT `tareas_ibfk_4` FOREIGN KEY (`id_propietario`) REFERENCES `usuarios` (`id_usuario`))
[Method: POST, Route: tareas/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Tareas` (`titulo`, `descripcion`, `fecha_vencimiento`, `fecha_creacion`, `fecha_actualizacion`) VALUES (:titulo:, :descripcion:, :fecha_vencimiento:, :fecha_creacion:, :fecha_actualizacion:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\TareaController.php(23): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TareaController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-08 19:03:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`sistemagestiontareas`.`tareas`, CONSTRAINT `tareas_ibfk_4` FOREIGN KEY (`id_propietario`) REFERENCES `usuarios` (`id_usuario`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Tareas` (`titulo`, `descripcion`, `fecha_vencimiento`, `fecha_creacion`, `fecha_actualizacion`) VALUES (\'La Primera\', \'111\', \'2025-05-08\', \'2025-05-08 19:03:07\', \'2025-05-08 19:03:07\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Tareas` (`titulo`, `descripcion`, `fecha_vencimiento`, `fecha_creacion`, `fecha_actualizacion`) VALUES (\'La Primera\', \'111\', \'2025-05-08\', \'2025-05-08 19:03:07\', \'2025-05-08 19:03:07\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Tareas` (`titulo`, `descripcion`, `fecha_vencimiento`, `fecha_creacion`, `fecha_actualizacion`) VALUES (:titulo:, :descripcion:, :fecha_vencimiento:, :fecha_creacion:, :fecha_actualizacion:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\TareaController.php(23): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TareaController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-08 19:03:08 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`sistemagestiontareas`.`tareas`, CONSTRAINT `tareas_ibfk_4` FOREIGN KEY (`id_propietario`) REFERENCES `usuarios` (`id_usuario`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `Tareas` (`titulo`, `descripcion`, `fecha_vencimiento`, `fecha_creacion`, `fecha_actualizacion`) VALUES (\'La Primera\', \'111\', \'2025-05-08\', \'2025-05-08 19:03:07\', \'2025-05-08 19:03:07\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Tareas` (`titulo`, `descripcion`, `fecha_vencimiento`, `fecha_creacion`, `fecha_actualizacion`) VALUES (\'La Primera\', \'111\', \'2025-05-08\', \'2025-05-08 19:03:07\', \'2025-05-08 19:03:07\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Tareas` (`titulo`, `descripcion`, `fecha_vencimiento`, `fecha_creacion`, `fecha_actualizacion`) VALUES (\'La Primera\', \'111\', \'2025-05-08\', \'2025-05-08 19:03:07\', \'2025-05-08 19:03:07\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Tareas` (`titulo`, `descripcion`, `fecha_vencimiento`, `fecha_creacion`, `fecha_actualizacion`) VALUES (:titulo:, :descripcion:, :fecha_vencimiento:, :fecha_creacion:, :fecha_actualizacion:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\TareaController.php(23): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TareaController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareaController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-05-08 19:14:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:15:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:16:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:16:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:16:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:17:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:17:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:49:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:50:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:52:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:53:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:54:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:56:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:58:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:58:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 20:58:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 21:01:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 21:01:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 21:04:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 21:04:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 21:04:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 21:04:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 21:04:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 21:04:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 21:06:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-08 21:47:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
